// dataService.js

export const names = [
  'Cozy Cottage',
  'Luxury Villa',
  'Modern Apartment',
  'Beach House',
  'Mountain Cabin',
  'Urban Flat',
  'Country House',
  'City Loft',
  'Historic Villa',
  'Modern Studio',
  'Seaside Bungalow',
  'Rustic Barn',
  'Downtown Condo',
  'Eco-friendly House',
  'Penthouse Suite',
  'Suburban Home',
  'Countryside Villa',
  'Lake Cabin',
  'Ski Lodge',
  'City Center Apartment',
]

export const types = [
  'Cottage',
  'Villa',
  'Apartment',
  'House',
  'Cabin',
  'Flat',
  'Loft',
  'Studio',
  'Bungalow',
  'Barn',
  'Condo',
  'Penthouse',
  'Home',
  'Lodge',
]

export const countries = [
  { name: 'Portugal', continent: 'Europe' },
  { name: 'Spain', continent: 'Europe' },
  { name: 'France', continent: 'Europe' },
  { name: 'Italy', continent: 'Europe' },
  { name: 'Switzerland', continent: 'Europe' },
  { name: 'Germany', continent: 'Europe' },
  { name: 'Netherlands', continent: 'Europe' },
  { name: 'United Kingdom', continent: 'Europe' },
  { name: 'Greece', continent: 'Europe' },
  { name: 'United States', continent: 'North America' },
  { name: 'Brazil', continent: 'South America' },
  { name: 'Argentina', continent: 'South America' },
  { name: 'Mexico', continent: 'North America' },
  { name: 'Canada', continent: 'North America' },
  { name: 'Japan', continent: 'Asia' },
  { name: 'China', continent: 'Asia' },
  { name: 'Australia', continent: 'Oceania' },
  { name: 'New Zealand', continent: 'Oceania' },
  { name: 'South Africa', continent: 'Africa' },
  { name: 'Kenya', continent: 'Africa' },
]

export const cities = {
  Portugal: ['Lisbon', 'Porto'],
  Spain: ['Barcelona', 'Valencia'],
  France: ['Paris', 'Marseille', 'Nice'],
  Italy: ['Naples', 'Rome', 'Milan'],
  Switzerland: ['Zurich', 'Geneva', 'Zermatt'],
  Germany: ['Berlin', 'Munich'],
  Netherlands: ['Amsterdam', 'Rotterdam'],
  'United Kingdom': ['London', 'Edinburgh'],
  Greece: ['Athens'],
  'United States': ['New York', 'Los Angeles', 'Chicago'],
  Brazil: ['Rio de Janeiro', 'Sao Paulo'],
  Argentina: ['Buenos Aires'],
  Mexico: ['Mexico City', 'Cancun'],
  Canada: ['Toronto', 'Vancouver'],
  Japan: ['Tokyo', 'Osaka'],
  China: ['Beijing', 'Shanghai'],
  Australia: ['Sydney', 'Melbourne'],
  'New Zealand': ['Auckland', 'Wellington'],
  'South Africa': ['Cape Town', 'Johannesburg'],
  Kenya: ['Nairobi'],
}

export const labels = [
  'Top of the world',
  'Trending',
  'Play',
  'Tropical',
  'Beach',
  'Beachfront',
  'Vineyards',
  'Mansions',
  'Lake',
  'Treehouses',
  'Farms',
  'Skiing',
  'Amazing pools',
  'Earth homes',
  'Amazing views',
  'Desert',
  'Lakefront',
  'Islands',
  'Camping',
  'Surfing',
  'Bed & breakfasts',
  'Luxe',
  'Ski-in/out',
]

export const imgUrls = [
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436975/hx9ravtjop3uqv4giupt.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436294/mvhb3iazpiar6duvy9we.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436496/ihozxprafjzuhil9qhh4.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436952/aef9ajipinpjhkley1e3.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436948/vgfxpvmcpd2q40qxtuv3.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436861/xrxhgsif3ekhxgn8irlm.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663437017/gjyzgdjngyrhfrj2loxz.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436556/mb70fifvvpvde8jub5cg.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663437241/wt0seud4ot4cmdrztdzz.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663437308/p80ndulkcghpcfsnvjdo.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436912/xle8ueqxjeazbs4bp09p.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436460/qi3vkpts37b4k0dedosc.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436481/tqwkxtbalipudzhivoag.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663437250/o8uutj3t2bvfafvxkr9j.jpg',
  'http://res.cloudinary.com/dmtlr2viw/image/upload/v1663436855/khyvb5q3yzcqaoscuppz.jpg',
]
